stages:
  preprocess:
    cmd: python src\preprocess.py
    deps:
    - data/raw/loan_data.csv
    - src/preprocess.py
    outs:
    - data/processed/processed_data.csv
  train:
    cmd: python src\train.py
    deps:
    - data/processed/processed_data.csv
    - params.yaml
    - src/train.py
    outs:
    - models/model.pkl
  evaluate:
    cmd: python src\evaluate.py
    deps:
    - data/processed/processed_data.csv
    - models/model.pkl
    - src/evaluate.py
    metrics:
    - metrics.json:
        cache: false
